# build
FROM node:12.12.0-alpine as build
WORKDIR /app
COPY package.json /app/package.json
RUN npm install 
COPY . /app
RUN npm run build

# ngnix deployment
FROM nginx:1.16.0-alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY --from=build /app/default.conf /etc/nginx/conf.d/
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
