export const auth = {
  username: 'user_1',
  modules: [
    {
      _id: '0001',
      title: 'Dashboard',
      href: '/dashboard',
    },
    {
      _id: '0002',
      title: 'List',
      href: '/list',
    },
  ],
};

export const list = [
  {
    _id: '1001',
    title: 'All New City',
    description: 'All New City',
    dimension: '4,549 mm L x 1,748 mm W x 1,489 mm H',
    color: 'red',
    price: '11.26 Lakh',
    imageUri: 'all-new-city.jpg',
  },
  {
    _id: '1002',
    title: 'Honda City',
    description: 'Honda City',
    dimension: '4,549 mm L x 1,748 mm W x 1,489 mm H',
    color: 'black',
    price: '15.18 Lakh',
    imageUri: 'city.png',
  },
  {
    _id: '1003',
    title: 'New Honda Amaze',
    description: 'All New City',
    dimension: '3,549 mm L x 1,558 mm W x 1,110 mm H',
    color: 'grey',
    price: '6.38 Lakh',
    imageUri: 'new-honda-amaze.png',
  },
  {
    _id: '1004',
    title: 'New Jazz',
    description: 'All New City',
    dimension: '3,988 mm L x 1,694 mm W x 1,544 mm H',
    color: 'white',
    price: '7.71 Lakh',
    imageUri: 'new-jazz.png',
  },
  {
    _id: '1005',
    title: 'WR-V',
    description: 'WR-V',
    dimension: '3,999 mm L x 1,734 mm W x 1,601 mm H',
    color: 'grey',
    price: '8.82 Lakh',
    imageUri: 'wrv.png',
  },
  {
    _id: '1006',
    title: 'All New City',
    description: 'All New City',
    dimension: '4,549 mm L x 1,748 mm W x 1,489 mm H',
    color: 'red',
    price: '11.26 Lakh',
    imageUri: 'all-new-city.jpg',
  },
  {
    _id: '1007',
    title: 'Honda City',
    description: 'Honda City',
    dimension: '4,549 mm L x 1,748 mm W x 1,489 mm H',
    color: 'black',
    price: '15.18 Lakh',
    imageUri: 'city.png',
  },
  {
    _id: '1008',
    title: 'New Honda Amaze',
    description: 'All New City',
    dimension: '3,549 mm L x 1,558 mm W x 1,110 mm H',
    color: 'grey',
    price: '6.38 Lakh',
    imageUri: 'new-honda-amaze.png',
  },
  {
    _id: '1009',
    title: 'New Jazz',
    description: 'All New City',
    dimension: '3,988 mm L x 1,694 mm W x 1,544 mm H',
    color: 'white',
    price: '7.71 Lakh',
    imageUri: 'new-jazz.png',
  },
  {
    _id: '1010',
    title: 'WR-V',
    description: 'WR-V',
    dimension: '3,999 mm L x 1,734 mm W x 1,601 mm H',
    color: 'grey',
    price: '8.82 Lakh',
    imageUri: 'wrv.png',
  },
];
